### ISSUE TITLE
Working on Windows?

### ISSUE THREAD

**Issue by SchlauFuchs** [0815fox/node-dependency-visualizer#5]
hi, 
calling  `node-dependency-visualizer` on Windows 10 leads to this error:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'ls', '--json' ]
}

```
I am using npm 7.0.7 on node v14.15.4

From the error message I assume this is depending on a linux environment?

**Comment by 0815fox** [comment]
The following line causes the error, however, it's strange, because I just try to spawn an npm command, and it says it can't find npm, which however should be on the path.

What console are you working on on windows?

Actually you're right, I work on linux and thus don't notice if it fails on windows. However I know that it used to work some time ago...

https://github.com/0815fox/node-dependency-visualizer/blob/82bef65104fba02eb40259151df012efa504205c/js/cli.js#L5

**Comment by MorgKrig** [comment]
Same problem as described from @SchlauFuchs here. Console is node.js and git bash.

**Comment by 0815fox** [comment]
Obviously a dependency I used was removed from npm (https://www.npmjs.com/package/child_process). Will replace it by something else.

**Comment by 0815fox** [comment]
Pull Request #7 

There seems to be a second issue: from version 7 of npm, `npm ls` needs an additional `--all`-flag to show deep dependencies.

**Comment by 0815fox** [comment]
New version 0.2.1 released.
